try ncc for packaging (#37)
* try ncc for packaging

* consistent

* newer checkout

* update dist

* update deps

* check style a different way

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,19 +8,19 @@ jobs:
     steps:
       # https://github.com/actions/checkout
       - name: Checkout
-        uses: actions/checkout@master
-        with:
-          fetch-depth: 1
+        uses: actions/checkout@v2
       - name: Install
         run: npm ci
       - name: Build
         run: npm run build
       - name: Test
         run: npm run test
-      - name: "check for uncommitted changes"
-        # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
-        run: |
-          git diff --exit-code --stat -- . ':!node_modules' \
-          || (echo "##[error] found changed files after build. please 'npm run build && npm run fmt'" \
-                  "and check in all changes" \
-              && exit 1)
+      - name: Format
+        run: npm run fmtcheck
+      # - name: "check for uncommitted changes"
+      #   # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
+      #   run: |
+      #     git diff --exit-code --stat -- . ':!node_modules' \
+      #     || (echo "##[error] found changed files after build. please 'npm run build && npm run fmt'" \
+      #             "and check in all changes" \
+      #         && exit 1)
